# Generated by Django 3.0.6 on 2020-05-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BugTicket',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('titles', models.CharField(max_length=60)),
                ('assigned', models.CharField(max_length=30)),
                ('reported', models.CharField(max_length=30)),
                ('ticket_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
